cat \
polyfill.es6.js \
basex.js \
unorm.js \
levenshtein.js \
kjua-0.1.1.min.js \
bitcoinjs-3.3.0.js \
bitcoinjs-extensions.js \
bitcoinjs-bip38-2.0.2.js \
segwit-parameters.js \
ethereumjs-util.js \
ripple-util.js \
sjcl-bip39.js \
wordlist_english.js \
wordlist_japanese.js \
wordlist_spanish.js \
wordlist_chinese_simplified.js \
wordlist_chinese_traditional.js \
wordlist_french.js \
wordlist_italian.js \
jsbip39.js \
biginteger.js \
zxcvbn.js \
entropy.js \
index.js \
> bip39all.js
